name: Build
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@main
      with:
        compiler: intel-classic
        version: 2021.9      
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_Fortran_COMPILER=ifort.exe -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Check Compilers and Versions
      run: |
        echo $env:FC
        cmake --version

    - name: Build Project
      run: cmake --build build

    - name: Run unit tests
      run: ctest --test-dir ${{github.workspace}}/build -C Debug
      
