name: Build
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: intel-classic
        version: 2021.9      
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure Project
      uses: threeal/cmake-action@v1.3.0

    - name: Build Project
      run: cmake --build build
