name: Build
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Install Fortran
      uses: fortran-lang/setup-fortran@main
      with:
        compiler: intel-classic
        version: 2021.9      
        
    - name: setvars.bat
      run: call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat --force"
        
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build Project
      run: cmake --build build

    - name: Run unit tests
      run: ctest --output-on-failure --test-dir ${{github.workspace}}/build -C Debug
      
